var localstore = 
{
    "0": {
        "top": 0,
        "left": 0,
        "width": "324px",
        "height": "314px",
        "border-radius": "0%",
        "z-index": "auto",
        "text-align": "center",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(110, 110, 10, 0)",
        "border-color": "rgb(220, 110, 10)",
        "border-width": "2px",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "",
        "html": "<div><img src=\"/Users/weiding/Sites/weidroot/weidroot_2017-01-06/app/github/wdingbox/phd03/Beijing_Guangjisi/20230416_Guangjisi_lion_wd.jpeg\" <=\"\" div=\"\"></div>"
    },
    "1": {
        "top": 919,
        "left": 148,
        "width": "80px",
        "height": "69px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "1",
        "html": "1"
    },
    "2": {
        "top": 933,
        "left": 235,
        "width": "57px",
        "height": "41px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "2",
        "html": "2"
    },
    "3": {
        "top": 693,
        "left": 153,
        "width": "75px",
        "height": "49px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "3",
        "html": "3"
    },
    "4": {
        "top": 958,
        "left": 304,
        "width": "79px",
        "height": "64px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "4",
        "html": "4"
    },
    "5": {
        "top": 678,
        "left": 306,
        "width": "69px",
        "height": "50px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "5",
        "html": "5"
    },
    "6": {
        "top": 913,
        "left": 364,
        "width": "96px",
        "height": "43px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "6",
        "html": "6"
    },
    "7": {
        "top": 1065,
        "left": 372,
        "width": "73px",
        "height": "44px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "7",
        "html": "7"
    },
    "8": {
        "top": 1123,
        "left": 449,
        "width": "65px",
        "height": "38px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "8",
        "html": "8"
    },
    "9": {
        "top": 566,
        "left": 380,
        "width": "74px",
        "height": "31px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "9",
        "html": "9"
    },
    "10": {
        "top": 1068,
        "left": 452,
        "width": "74px",
        "height": "31px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "10",
        "html": "10"
    },
    "11": {
        "top": 565,
        "left": 530,
        "width": "74px",
        "height": "31px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "11",
        "html": "11"
    },
    "12": {
        "top": 628,
        "left": 530,
        "width": "74px",
        "height": "31px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "12",
        "html": "12"
    },
    "13": {
        "top": 1001,
        "left": 526,
        "width": "76px",
        "height": "46px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "13",
        "html": "13"
    },
    "14": {
        "top": 1110,
        "left": 517,
        "width": "84px",
        "height": "35px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "14",
        "html": "14"
    },
    "15": {
        "top": 920,
        "left": 740,
        "width": "88px",
        "height": "74px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "15",
        "html": "15"
    },
    "16": {
        "top": 1095,
        "left": 667,
        "width": "84px",
        "height": "35px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "16",
        "html": "16"
    },
    "17": {
        "top": 651,
        "left": 665,
        "width": "84px",
        "height": "35px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "17",
        "html": "17"
    },
    "18": {
        "top": 1169,
        "left": 587,
        "width": "84px",
        "height": "35px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "18",
        "html": "18"
    },
    "19": {
        "top": 934,
        "left": 590,
        "width": "84px",
        "height": "35px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "19",
        "html": "19"
    },
    "20": {
        "top": 781,
        "left": 593,
        "width": "84px",
        "height": "35px",
        "border-radius": "50%",
        "border-width": "5px",
        "border-color": "rgb(220, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "20",
        "html": "20"
    },
    "21": {
        "top": 189,
        "left": 205,
        "width": "194px",
        "height": "179px",
        "border-radius": "0%",
        "border-width": "1px",
        "border-color": "rgb(256, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "21",
        "html": "21"
    },
    "22": {
        "top": 306,
        "left": 467,
        "width": "77px",
        "height": "107px",
        "border-radius": "0%",
        "border-width": "1px",
        "border-color": "rgb(0, 0, 0)",
        "z-index": "auto",
        "text-align": "start",
        "font-size": "16px",
        "opacity": "1",
        "background-color": "rgba(0, 0, 0, 0)",
        "rotate": "none",
        "writing-mode": "horizontal-tb",
        "text": "22",
        "html": "22"
    }
}